### ISSUE TITLE
"make" fails with error

### ISSUE THREAD

**Issue by ahlstromcj** [jean-emmanuel/seq192#11]
On a fresh git clone, "make" yields this error:

src/core/configfile.cpp:18:10: fatal error: nlohmann/json.hpp: No such file or directory
   18 | #include <nlohmann/json.hpp>

**Comment by ahlstromcj** [comment]
README!!!?  Who reads that stuff!  :-D <blush>.  I found that package in the Ubuntu repo, and now the build works fine.

One weird thing is that seq192.cpp has the executable bits set.

**Comment by ahlstromcj** [comment]
Actually a lot of headers and cpp's have the exe bits on.  No biggie.

**Comment by jean-emmanuel** [comment]
Weird indeed, now fixed :)
