### ISSUE TITLE
Scrolling in piano roll doesn't work

### ISSUE THREAD

**Issue by tentaclius** [jean-emmanuel/seq192#15]
I was checking the code in attempt to find a way to zoom the piano roll area in and out and to my surprise I found that there should be zoom by Ctrl+Scroll, I didn't know this is a feature. Unfortunately, it doesn't work in my build at all. It looks like EditWindow::scroll_callback() never gets called.
In my case scrolling only works in PianoKeys for some reason. Any idea what could be the case or how do I troubleshoot it further?
I'm running Fedora 36, gcc 12.2.1 20220819, gtkmm-2.4. 

Linking options: g++ -o src/seq192 src/core/cachefile.o src/core/configfile.o src/core/event.o src/core/midibus.o src/core/midifile.o src/core/mutex.o src/core/osc.o src/core/perform.o src/core/sequence.o src
/gui/dataroll.o src/gui/editwindow.o src/gui/eventroll.o src/gui/mainwindow.o src/gui/pianokeys.o src/gui/pianoroll.o src/gui/sequencebutton.o src/gui/timeroll.o src/seq192.o -llo -L/usr/lib6
4/pipewire-0.3/jack -ljack -lasound -lgtkmm-3.0 -latkmm-1.6 -lgdkmm-3.0 -lgiomm-2.4 -lgtk-3 -lgdk-3 -latk-1.0 -lcairo-gobject -lgio-2.0 -lpangomm-1.4 -lglibmm-2.4 -lcairomm-1.0 -lsigc-2.0 -lp
angocairo-1.0 -lpango-1.0 -lharfbuzz -lcairo -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0

P.S. Thanks for this beautiful peace of software!

**Comment by jean-emmanuel** [comment]
Scrolling and zooming should work like this, at least it does here:
- above the keys, vertical scrolling only, no zooming
- anywhere else, horizontal zooming (ctrl+wheel), vertical scrolling (wheel) and horizontal scroll (shift+wheel) except in the top area where only horizontal scrolling is possible

I'll try to build it on an up to date system, just in case it's something to to with a change in gtk (I doubt it though). What window manager do you use ? I've only been testing seq192 on xfce and i3 so far so there might be some overlooked spot.

**Comment by tentaclius** [comment]
Yep,
- Scrolling over the keys works, no zooming.
- Scrolling anywhere else doesn't, not even in the top area. Scrolling with Ctrl or Shift also does nothing.
I'm currently on Gnome 42.4. I'll try it on dwm or xfce a bit later.
Scrolling in the main window does work.

**Comment by tentaclius** [comment]
Oh, forgot to mention. This Fedora/Gnome versions use Wayland. I bet it might be involved... I'll try on X11

**Comment by jean-emmanuel** [comment]
I suspected something like that too..

**Comment by tentaclius** [comment]
Checked on X11. Does work fine. Strange thing it doesn't on Wayland. The code looks pretty straightforward. I'll try to find any info on how scrolling on Wayland should be handled. Thanks.

**Comment by jean-emmanuel** [comment]
Can you try this ? https://docs.gtk.org/gtk3/wayland.html

Le 03/10/2022 à 11:33, Anton Erdman a écrit :

**Comment by tentaclius** [comment]
> Can you try this ? https://docs.gtk.org/gtk3/wayland.html 

Still the same issue with scrolling with GDK_BACKEND set to "wayland".

**Comment by tentaclius** [comment]
It does work well if set to "x11" though:
GDK_BACKEND=x11 ./src/seq192

I found it was mentioned in Remmina discussion that this is a known GDK on Wayland bug. It seems that seq192 is not related and there is nothing to fix. Thanks!

**Comment by jean-emmanuel** [comment]
great ! have fun with it then :)

Le 03/10/2022 à 12:41, Anton Erdman a écrit :
