### ISSUE TITLE
Midi aftertouch always sent with Note 0 (C-1)

### ISSUE THREAD

**Issue by Houston4444** [jean-emmanuel/seq192#17]
Maybe I miss something, this is the first time I try to use aftertouch messages, but all aftertouch messages sent from seq192 are affected to the lower note (0, C-1). Maybe there is a graphical solution for that but I don't see it.

**Comment by jean-emmanuel** [comment]
As far as I can tell the bug was already in seq24. I don't think the UI is suited for polyphonic pressure actually, I'll probably just remove the entry from the menu as I don't  think it's worth extending the UI for one event type.

**Comment by jean-emmanuel** [comment]
Actually a proper fix would be to add a sub-menu like the one for control changes so that each key pressure event can be controlled individually.

**Comment by Houston4444** [comment]
Yes, it would be correct. For an intuitive usage, there would be better to do, but this is really a niche case, so an overrated dev time.

**Comment by jean-emmanuel** [comment]
Done
