### ISSUE TITLE
Map "Trigger Record"  to MIDI/OSC

### ISSUE THREAD

**Issue by CarloCattano** [jean-emmanuel/seq192#2]
Hello there ! 
Thanks a lot for this retake at seq. It runs super well on my tiny raspberry pi 3 . Im aiming for a touchscreen setup only to use a midi looper and this looks promising .

One thing Im missing or not finding in docs , is the ability to map the record trigger of a clip . Its very much needed for live performing etc . 

Thanks again

**Comment by jean-emmanuel** [comment]
Hey ! I'm really pleased someone uses this :). The function is not osc controllable currently but it will be very easy to add and definitely makes sense.

**Comment by CarloCattano** [comment]
Im having a look at the code and learning a lot from it already. I see the calls to performer on the osc callbacks and few other pieces, looks doable indeed.

 Not sure about the approach. All the prev versions including modern ones have this missing key feature.
Perhaps a global record button and individual arming, or per clip. Midi is what I usually use the most BUT this lightweight version can be huge combined with something like touchOSC and alikes, since it even takes messages back and can update the UI via osc 💣💣

**Comment by jean-emmanuel** [comment]
In the current state of the engine, only one sequence can be armed at a time, this limitation has been removed in seq66 but I'm not sure I'll try to implement it here; I think I'll add two control modes for sequences:
`/sequence record_on <sequence_name_or_position>`
and
`/sequence record_off`

**Comment by CarloCattano** [comment]
This would be more than enough , and exactly whats needed ! 
Thanks a lot for the efforts

**Comment by jean-emmanuel** [comment]
It's in sources now you can build and test it.

**Comment by jean-emmanuel** [comment]
By the way, there's a FLOSS alternative to touchosc : https://github.com/jean-emmanuel/open-stage-control
I've made a web ui with it when working on seq192, I just have  to clean it a bit some day before uploading it.

**Comment by CarloCattano** [comment]
Indeed i found out yesterday about open stage contro, looks very neat. I will pull and check the new function wohoo!

**Comment by CarloCattano** [comment]
It works flawlessly , can say closed and big thanks
