### ISSUE TITLE
Pitch wheel events limits should be -8192 to +8191

### ISSUE THREAD

**Issue by Houston4444** [jean-emmanuel/seq192#21]
The error was probably already in seq24, the pitch wheel events have incorrect values from 0 to 127, this should be -8192 to +8191 (or 0 to 16383, but I prefer the signed type, because 0 is neat for 0 pitch modification).
More, the value sent is incorrect (the 0 on pitch bend event is not at 64 but at 94, 127 gives +6144), making it very hard to use.

**Comment by jean-emmanuel** [comment]
The pitch calculation is wrong indeed, however I'd rather keep the fake display range to prevent bloating the UI.

**Comment by jean-emmanuel** [comment]
Actually it's not that wrong, it's just that the least significant bit is not taken into account. I'm not getting the same result though, I get 0 at 64 but only 8064 at 127 (127 from the LSB missing there).

**Comment by Houston4444** [comment]
I don't really understand, I have quite random results. I imagine that the second 7bits numbers has been set for this control because we could ear the stairway with only 128 steps.

**Comment by jean-emmanuel** [comment]
I'm working on it, but the 128 steps will remain, there's only 127 pixels there.

**Comment by jean-emmanuel** [comment]
I changed the slider's origin to help visualizing the value. I fixed the range by forcing the last step (127) to 8192. I could reproduce the other results you got so if it occurs again please attach your midi file.
Note that this limitation is only applied when changing the value from the gui, recorded pitch wheel events should have the full precision (and will lose it once modified in the gui).

**Comment by Houston4444** [comment]
Thanks a lot, that's quite perfect, the new centered origin make it very very much clear.
The random results I had came from the plugin I am writing (something really bad coded that change the velocity and also accidentally applies to the pitch wheel ;)).
