### ISSUE TITLE
Question: How should I manage to change phase with a rythmic signature to another one ?

### ISSUE THREAD

**Issue by Houston4444** [jean-emmanuel/seq192#22]
It is a question, not a bug report or a feature request.

When an entire song in composed of 4/4 measures, there is no problem, we can switch from one group of sequences to another one, directly or with queue event, the next group of sequences will be correctly aligned, no problem in both cases.

But suppose I am on a loop in 7/4, and I want to switch to another group of sequences in 4/4, if I switch directly, there are many chances that the sequences in 4/4 are not at the good position, and the same problem exists if I order queue events.

The only solution I see is to calculate the exact position of the first beat of the 4/4, with infos I have (when I started play and tempo). I could have more position infos using JACK transport but I am really not sure I will have measures durations.

Have you ever been confronted with this case ?

**Comment by jean-emmanuel** [comment]
I have the same use case and I usually solve it either by restarting the playback on the first beat when the change of sequence must occur, this works very well when playing real instruments at the same time and forces the machines to follow the human musical time feel. When I need some scripted sequence change I have a 3rd-party engine ([mentat](https://jean-emmanuel.github.io/mentat/)) that holds a "master" time signature and a steady clock I can use to send osc messages on predefined beats, it works well too but needs some time to get used too.

I don't use the queue feature from seq24, and in its current state it doesn't support changing the metric. It may be improved toward that though by adding two things
- a settable reference sequence for queues (for instance, you'd want to set a 4/4 reference for queuing a 7/4 sequence)
- the possibility for queued sequences to be indivdually triggered when their queue reference reach its end (which kinda messes with how sequences are sync'd, but it may be harmless)

**Comment by Houston4444** [comment]
Thanks for this detailed answer. Indeed, I will try the restart the playback when the control changing the sequences is triggered, the thing that worries me most about this technique is ugly double hits if I press the control a little too late, It is better to play it a little bit before the time to prevent that.

Another thing maybe doable is to have another message similar to /sequence/trig, but that operates only on the next beat, this way the player has one beat to send it, without breaking the flow. It may be incompatible with different sequence signature divisions (e.g. switching for 4/4 to 7/8), but in real life, I am pretty sure near nobody compose this kind of things ;).

If I am not happy with the first solution, I may try mentat !

**Comment by jean-emmanuel** [comment]
I just pushed a bunch of changes that make it possible from seq192 : try shift+clicking a sequence to define it as the sync reference, and ctrl+clicking another to queue it. There's probably some debugging left, but it seems close.

**Comment by jean-emmanuel** [comment]
(i doesn't work yet actually !:)

**Comment by Houston4444** [comment]
I think the new "sync" option solves entirely the problem. It is just perfect !
Thanks a lot again !
