### ISSUE TITLE
Packages for Fedora

### ISSUE THREAD

**Issue by JamesFrederik** [jean-emmanuel/seq192#23]
these are the packages to build on fedora

pipewire-jack-audio-connection-kit-devel alsa-lib-devel liblo-devel gtkmm30-devel json-devel

**Comment by jean-emmanuel** [comment]
Thanks for the report, I'm a little skeptic regarding  `pipewire-jack-audio-connection-kit-devel` though, shouldn't `jack-audio-connection-kit-devel` do just as well ?

**Comment by JamesFrederik** [comment]
Yeah I'm sure it's fine. You can only have one of the two installed at once so I use the pipewire version as pipewire is default now on Fedora and I need it to compile stuff that uses the pipewire bits.

**Comment by jean-emmanuel** [comment]
Thanks, readme updated.
