### ISSUE TITLE
midi editing a bit cumbersome

### ISSUE THREAD

**Issue by grammoboy2** [jean-emmanuel/seq192#24]
Nice tool. Feels a bit cumbersome though using 2 mouse buttons to insert midi. Would also be nice to be able to remove midi entry with one key. 

Was this one of the reasons non-sequencer was build as seq24 replacement? Might be worth to take a look at non-sequencer then and see if midi editing in seq192 could be made a bit more fluent. 

Note, I've little experience with seq192 yet. At first sight I like how one can edit the velocity quite easily.

**Comment by jean-emmanuel** [comment]
Thanks !

Right click + left click to insert notes is one of the reason I always preferred seq24 over the others, I guess it depends on one's tastes but I'd rather keep it that way. As much as I love the non-* suite  (long time user of non-mixer here), I must admit non-sequencer never got to a point where it could be of any use to me, and I doubt it ever will, because seq24/seq192 *just works*.

Disclaimer: Seq192 is a very opinionated fork driven with specific use cases in mind, it may be frustrating but it has no ambition to reach a wider audience although I'm very happy it can be of any use out there. Small features may be added of course, but I'll try my best to keep the "less features" spirit alive, because as far as I'm concerned this software is pretty much completed for me.

**Comment by jean-emmanuel** [comment]
> Would also be nice to be able to remove midi entry with one key.

Do you mean you'd like to be able to remove a note without selecting it first ? Pressing Del/Backspace while hovering a note/event would remove it if no other event is selected ?

**Comment by grammoboy2** [comment]
> Pressing Del/Backspace while hovering a note/event would remove it if no other event is selected ?

I don't see how this works, sorry.

> but I'll try my best to keep the "less features" spirit alive

That's why I try it out ;) Quite some tools have too many quirks.

**Comment by jean-emmanuel** [comment]
>>Pressing Del/Backspace while hovering a note/event would remove it if no other event is selected ?

>I don't see how this works, sorry.

I'm only trying to guess what you meant in the first place, please explain if I got it wrong.

**Comment by grammoboy2** [comment]
> > 
> 
> Do you mean you'd like to be able to remove a note without selecting it first ? 

yes

> Pressing Del/Backspace while hovering a note/event would remove it if no other event is selected ?

I'm only able to remove a note after it is selected

**Comment by grammoboy2** [comment]
The ability to set custom keybindings wouldn't be bad. Escape is so far away... :)

**Comment by jean-emmanuel** [comment]
I don't think I'll add custom keybindings, it's too much effort for a feature that's out of scope anyway (the gui is meant for editing, not for live perfomance). I had thought of adding an extra keybinding for stop though, something like ctrl+space.

**Comment by jean-emmanuel** [comment]
Both the aforementioned changes are now in sources.

**Comment by grammoboy2** [comment]
Works, thx. 

It's still hard for me to see why one needs two mouse buttons for the most important and most frequent action, inserting midi. On a laptop this is close to impossible. Ok, because that one mouse button is reserved for selecting...

I would say, let inserting midi be done with one button and add the need of that extra button to selecting, alt + left-mouse-button for instance. Or selecting by holding the left-mouse-button? What are other sequencers doing? Non-sequencer and qtractor do have a 'select mode' it seems. If you could toggle that with a button. Anything would work, if at least midi editing can be done with a single button. :)

In non-sequencer (and patroneo) hitting an already entered note, will removed it. Makes sense. Using the right mouse-button for removing the entered midi note, was another intuitive thing I tried, but didn't work in any of the mentioned sequencers.

**Comment by jean-emmanuel** [comment]
The draw mode can now be switched to using a dedicated toggle button and the "d" key.
