### ISSUE TITLE
Feature request: "rename" shortcut and dialog

### ISSUE THREAD

**Issue by Houston4444** [jean-emmanuel/seq192#26]
Rename sequences can be quite boring when we are renaming them massively.
The current steps are:
* right click -> edit (or middle click)
* move the cursor to the name input
* Select all the field (if needed)
* type the new name
* press Enter
* close the edition window (if needed)

A rename shortcut in the context menu would allow to do the same thing faster
* right click -> rename (or maybe F2)
* type the new name (input field has focus and all field content is selected)
* press enter (it closes the rename dialog)

**Comment by jean-emmanuel** [comment]
Done !

**Comment by Houston4444** [comment]
Nice ! Thanks.
There is a little bug though, if editor window of the sequence is open, the name label is not updated in this window once the sequence has been renamed by rename dialog.

**Comment by jean-emmanuel** [comment]
thanks, fixed

Le 05/03/2023 à 19:06, Houston4444 a écrit :

**Comment by Houston4444** [comment]
Thanks ! Works great.
