### ISSUE TITLE
New Recorded Notes dont show up in Editor 

### ISSUE THREAD

**Issue by CarloCattano** [jean-emmanuel/seq192#3]
I'm getting a weird behavior that is a show-stopper  . 

[Example 1]
Open up seq192 
make a clip with notes and send to ch 1 
Play it back 
While Its playing toggle Record and play some notes on the controller.
The notes record successfully and midi is sent out as played , but the new notes are not displayed on the piano roll.

[Example 2]
Try with a new clip . Assign it to an output .
Play it back empty and toggle record while it plays 
You got your loop , but the clip looks empty .

Screenshots  : 
[example 1 ]
![image](https://user-images.githubusercontent.com/17380530/132641977-611934d2-cc28-4c87-b4d5-99cbb554f9fc.png)
Initial notes + recorded material that comes out ( but we cant see it in the picture, only the initial hand-drawn notes visible)

[example 2]
![image](https://user-images.githubusercontent.com/17380530/132642245-df9e0525-b041-49c4-ad01-b1b31a8f911c.png)

[ 1 & 2 next to each other ] 
![image](https://user-images.githubusercontent.com/17380530/132642398-e8ccdedd-12cf-4275-adc2-4a9201c4d47b.png)

 jack routes
![image](https://user-images.githubusercontent.com/17380530/132642499-3bbcd1e9-3a82-4741-98df-dd18478612ee.png)

seq192 sends to Carla in this case with 2 instruments in ch 1 & 2 respectively

**Comment by CarloCattano** [comment]
***An extra clue seems to be that clips that have "invisible notes" , always result in hanging note on's if the clip is muted while playing or anyhow. Patterns that are maually drawn dont have this issue

**Comment by CarloCattano** [comment]
Alright . Saving the file , and opening it up again confirms that it is only a visual problem .
The Notes are there when the file is reloaded . This is the same set , just added 2 more clips for testing but 1 and 2 are there intact

![image](https://user-images.githubusercontent.com/17380530/132645677-cf393162-23fb-4549-9c75-b76c3cd973c2.png)

**Comment by jean-emmanuel** [comment]
Thanks, I'll take a look at it soon.

Le 09/09/2021 à 09:53, Qwrtst a écrit :

**Comment by jean-emmanuel** [comment]
Weird, I did not manage to reproduce the issue, here the notes are drawn as expected, are you confident it's not just a matter of octave ? An easy way to check this is the presence of note_on events just under the piano roll section. Just in case, In your screenshot the transport is stopped, but it was running when recording, right ?

**Comment by CarloCattano** [comment]
Yes it was running on recording, i just stopped to take sceeenshots.
Maybe it's something to do with my pi OS or something. Will try again.
As you see in the Screenshots, even the clip box is empty. It's only filled up on next load (save, close and open)

**Comment by CarloCattano** [comment]
Sorry for the low quality in both video and recording , I had to trim it down to be able to upload ~10mb
https://user-images.githubusercontent.com/17380530/132725889-d44a88ab-2af5-43e6-bd7e-f6bf602890ee.mp4

**Comment by jean-emmanuel** [comment]
Thanks, one thing you didn't do in the video is closing the edit window before opening it (it's only in the background), does it change anything ? It could be a issue with the OS indeed, I'm new to gtk3 and could have missed something here.

**Comment by CarloCattano** [comment]
Just tried , nothing different  .
Also It is not "only" a GUI issue Im afraid, because of the hanging notes on stopping the clip (doesnt happen on regular clips) , it looks like its even worst than that , or the GUI conexion with the code is messing the midi up

**Comment by jean-emmanuel** [comment]
Can you check if the keyboard sends any extra events other than notes during the recording ? I've been testing with a simple virtual keyboard but maybe there's something wrong happening with specific midi events.

**Comment by jean-emmanuel** [comment]
I just push a small change that prevents writing sysex message in sequences, in case it's related (and if not, it seems reasonable to do so anyway).

**Comment by CarloCattano** [comment]
Unfortunately nothign changed . I just double checked with MIDI-OX and I dont send any other data apparently :-(
Sorry not trying to stress you out !

**Comment by CarloCattano** [comment]
Interesting ! same as you , when I send from PureData for example it works as it should , it must be mi midi controller but wow. starting to get interesting 

![image](https://user-images.githubusercontent.com/17380530/132746686-fd79d30a-398e-4565-a8fd-68a588978ed6.png)

**Comment by CarloCattano** [comment]
OK Consider it CLOSED !!
For some reason , if the controller has any other midi CH than 1 it wont work for me here  .
I changed the CH on the controller and now I can record and see the notes coming in  real time . 
Could be nice to change that , or directly just only use ch one and let users filter/re-route themselves .

**Comment by jean-emmanuel** [comment]
Nice catch ! IIRC the channel information is supposed to be ignored and striped out when recording, now I know what to fix :)
