### ISSUE TITLE
Jack transport set BPM

### ISSUE THREAD

**Issue by zigmhount** [jean-emmanuel/seq192#34]
Hello,

As far as I understand, Seq192 can only be a Jack timebase client. When Jack transport is activated, it is not possible to change the tempo in Seq192. I thought that this was simply not possible for a Jack client, but according to https://jackaudio.org/api/structjack__position__t.html I understand that it should be possible for a jack client to change the tempo of the master, correct?
Is this not possible with Seq192 because you have implemented only the state aspect but not any repositioning, as suggested in the "JACK TRANSPORT" section of the man page? or is it just an oversight - in which case I could try to look into it?

Thanks!

**Comment by jean-emmanuel** [comment]
It may not be specified cleary but it really doesn't feel right for a regular client to change the tempo and I'm pretty sure any client registering as the timebase master will not read tempo changes submitted by other clients.
