### ISSUE TITLE
Note division not remembered for each piano roll dialog

### ISSUE THREAD

**Issue by Houston4444** [jean-emmanuel/seq192#36]
Experimenting a song with 3 divisions per beat, i meet a very annoying thing, each time I close/reopen a sequence pianoroll, the beat division is forgotten and beat/4 (1/16) is the default display, and of course, I would want beat/3 (1/12) .

I don't know what would be the best behavior, but at least, save the division for each sequence. And maybe, for a new sequence, set the division to the last division used in the page.

**Comment by jean-emmanuel** [comment]
done !

**Comment by Houston4444** [comment]
Yeah, not tested yet but thanks you very much !
