### ISSUE TITLE
[feature] Ableton Link support

### ISSUE THREAD

**Issue by grammoboy2** [jean-emmanuel/seq192#9]
So you can sync with other applications like Renoise, Tidal Cycles, Pd, Bitwig etc. 
https://lac.linuxaudio.org/2018/pages/event/42/

edit: maybe useful: https://github.com/falkTX/Hylia

**Comment by jean-emmanuel** [comment]
I'm closing the ticket as there is little chance I'll ever do something about it, jack_link looks like a fine solution and matches how I "less is more" I'd like to keep seq192.
